import type { DpStateDefinition } from "./types";

export const HEAT_PUMP_CATEGORY_CODE = "heatPump";
export const WATER_PUMP_CATEGORY_CODE = "waterPump";

export const HEAT_HVAC_MODES: Record<number, string> = {
  0: "auto",
  1: "heat",
  2: "cool",
};

export const HEAT_HVAC_MODE_STATES: Record<string, string> = {
  off: "Off",
  auto: "Auto",
  heat: "Heat",
  cool: "Cool",
};

export const WATER_PUMP_MODE_LABEL_TO_OPTION: Record<string, string> = {
  AI: "auto_inverter",
  MI: "manual_inverter",
  backwash: "backwash",
};

export const WATER_PUMP_MODE_FALLBACK: Record<number, string> = {
  0: "manual_inverter",
  1: "backwash",
};

export const HEAT_PUMP_POWER_DP_ID = "101";
export const HEAT_PUMP_PRESET_DP_ID = "102";
export const HEAT_PUMP_CURRENT_TEMP_DP_ID = "103";
export const HEAT_PUMP_HVAC_MODE_DP_ID = "106";
export const HEAT_PUMP_TARGET_TEMP_DP_ID = "107";
export const HEAT_PUMP_ACTION_DP_ID = "113";

export const WATER_PUMP_MODE_DP_ID = "103";
export const WATER_PUMP_POWER_DP_ID = "105";

export const HEAT_PUMP_SENSOR_DEFINITIONS: DpStateDefinition[] = [
  {
    id: "temperature.current",
    dpId: HEAT_PUMP_CURRENT_TEMP_DP_ID,
    name: "Inlet water temperature",
    role: "value.temperature",
    type: "number",
    unit: "°C",
    useDpScale: true,
  },
  {
    id: "temperature.outlet",
    dpId: "129",
    name: "Outlet water temperature",
    role: "value.temperature",
    type: "number",
    unit: "°C",
    useDpScale: true,
  },
  {
    id: "temperature.ambient",
    dpId: "130",
    name: "Ambient temperature",
    role: "value.temperature",
    type: "number",
    unit: "°C",
    useDpScale: true,
  },
  {
    id: "temperature.exhaust",
    dpId: "131",
    name: "Exhaust temperature",
    role: "value.temperature",
    type: "number",
    unit: "°C",
    useDpScale: true,
  },
  {
    id: "temperature.outerCoilPipe",
    dpId: "132",
    name: "Outer coil pipe temperature",
    role: "value.temperature",
    type: "number",
    unit: "°C",
    useDpScale: true,
  },
  {
    id: "temperature.gasReturn",
    dpId: "133",
    name: "Gas return temperature",
    role: "value.temperature",
    type: "number",
    unit: "°C",
    useDpScale: true,
  },
  {
    id: "temperature.innerCoilPipe",
    dpId: "134",
    name: "Inner coil pipe temperature",
    role: "value.temperature",
    type: "number",
    unit: "°C",
    useDpScale: true,
  },
  {
    id: "temperature.coolingPlate",
    dpId: "135",
    name: "Cooling plate temperature",
    role: "value.temperature",
    type: "number",
    unit: "°C",
    useDpScale: true,
  },
  {
    id: "runningPercentage",
    dpId: "105",
    name: "Running percentage",
    role: "value",
    type: "number",
    unit: "%",
  },
  {
    id: "power.current",
    dpId: "112",
    name: "Power",
    role: "value.power",
    type: "number",
    unit: "kW",
    scale: 3,
    useDpScale: true,
  },
  {
    id: "fan.dcSpeed",
    dpId: "137",
    name: "DC fan speed",
    role: "value",
    type: "number",
    unit: "r/min",
  },
  {
    id: "valve.electronicExpansionOpening",
    dpId: "136",
    name: "Electronic expansion valve opening",
    role: "value",
    type: "number",
  },
  {
    id: "diagnostic.lowerTemperatureLimit",
    dpId: "108",
    name: "Lower temperature limit",
    role: "value.temperature",
    type: "number",
    unit: "°C",
    useDpScale: true,
  },
  {
    id: "diagnostic.upperTemperatureLimit",
    dpId: "109",
    name: "Upper temperature limit",
    role: "value.temperature",
    type: "number",
    unit: "°C",
    useDpScale: true,
  },
  {
    id: "diagnostic.powerDisplayStatus",
    dpId: HEAT_PUMP_ACTION_DP_ID,
    name: "Power display status",
    role: "value",
    type: "number",
  },
  {
    id: "diagnostic.refrigerationFunction",
    dpId: "114",
    name: "Refrigeration function",
    role: "value",
    type: "number",
  },
  {
    id: "diagnostic.overclockingFunction",
    dpId: "115",
    name: "Overclocking function",
    role: "value",
    type: "number",
  },
  {
    id: "diagnostic.waterPumpRunningMode",
    dpId: "116",
    name: "Water pump running mode",
    role: "value",
    type: "number",
  },
  {
    id: "diagnostic.waterPumpRunningTime",
    dpId: "117",
    name: "Water pump running time",
    role: "value",
    type: "number",
    unit: "min",
  },
  {
    id: "diagnostic.defrostingInterval",
    dpId: "118",
    name: "Defrosting interval",
    role: "value",
    type: "number",
    unit: "min",
  },
  {
    id: "diagnostic.defrostingStartTemperature",
    dpId: "119",
    name: "Defrosting start temperature",
    role: "value.temperature",
    type: "number",
    unit: "°C",
    useDpScale: true,
  },
  {
    id: "diagnostic.defrostingRunningTime",
    dpId: "120",
    name: "Defrosting running time",
    role: "value",
    type: "number",
    unit: "min",
  },
  {
    id: "diagnostic.defrostingQuitTemperature",
    dpId: "121",
    name: "Defrosting quit temperature",
    role: "value.temperature",
    type: "number",
    unit: "°C",
    useDpScale: true,
  },
  {
    id: "diagnostic.compressorSpeedControl",
    dpId: "122",
    name: "Compressor speed control",
    role: "value",
    type: "number",
  },
  {
    id: "diagnostic.eevSuperheatHeating",
    dpId: "123",
    name: "EEV superheat heating",
    role: "value.temperature",
    type: "number",
    unit: "°C",
    useDpScale: true,
  },
  {
    id: "diagnostic.eevSuperheatCooling",
    dpId: "124",
    name: "EEV superheat cooling",
    role: "value.temperature",
    type: "number",
    unit: "°C",
    useDpScale: true,
  },
  {
    id: "diagnostic.eevControlMode",
    dpId: "125",
    name: "EEV control mode",
    role: "value",
    type: "number",
  },
  {
    id: "diagnostic.eevManualOpeningHeating",
    dpId: "126",
    name: "EEV manual opening heating",
    role: "value",
    type: "number",
  },
  {
    id: "diagnostic.eevManualOpeningCooling",
    dpId: "127",
    name: "EEV manual opening cooling",
    role: "value",
    type: "number",
  },
  {
    id: "diagnostic.powerOffMemoryFunction",
    dpId: "128",
    name: "Power-off memory function",
    role: "value",
    type: "number",
  },
];

export const HEAT_PUMP_NUMBER_DEFINITIONS: DpStateDefinition[] = [
  {
    id: "config.waterPumpMode",
    dpId: "116",
    name: "Set water pump mode",
    role: "level",
    type: "number",
    write: true,
    min: 0,
    max: 2,
    step: 1,
    useDpRange: true,
  },
  {
    id: "config.waterPumpTime",
    dpId: "117",
    name: "Set water pump time",
    role: "level.timer",
    type: "number",
    unit: "min",
    write: true,
    min: 10,
    max: 120,
    step: 5,
    useDpRange: true,
  },
  {
    id: "config.defrostingInterval",
    dpId: "118",
    name: "Set defrosting interval",
    role: "level.timer",
    type: "number",
    unit: "min",
    write: true,
    min: 30,
    max: 90,
    step: 1,
    useDpRange: true,
  },
  {
    id: "config.defrostingStartTemperature",
    dpId: "119",
    name: "Set defrosting start temperature",
    role: "level.temperature",
    type: "number",
    unit: "°C",
    write: true,
    min: -30,
    max: 250,
    step: 1,
    useDpRange: true,
  },
  {
    id: "config.defrostingRunningTime",
    dpId: "120",
    name: "Set defrosting running time",
    role: "level.timer",
    type: "number",
    unit: "min",
    write: true,
    min: 1,
    max: 12,
    step: 1,
    useDpRange: true,
  },
  {
    id: "config.defrostingQuitTemperature",
    dpId: "121",
    name: "Set defrosting quit temperature",
    role: "level.temperature",
    type: "number",
    unit: "°C",
    write: true,
    min: 8,
    max: 100,
    step: 1,
    useDpRange: true,
  },
];

export const WATER_PUMP_SENSOR_DEFINITIONS: DpStateDefinition[] = [
  {
    id: "power.current",
    dpId: "5",
    name: "Current power",
    role: "value.power",
    type: "number",
    unit: "W",
    useDpScale: true,
  },
  {
    id: "pump.runningRate",
    dpId: "102",
    name: "Running rate",
    role: "value",
    type: "number",
    unit: "%",
    requireValue: true,
  },
  {
    id: "pump.backwashCountdown",
    dpId: "108",
    name: "Backwash countdown",
    role: "value.interval",
    type: "number",
    unit: "min",
    useDpTimeUnit: true,
  },
  {
    id: "energy.consumption",
    dpId: "109",
    name: "Energy consumption",
    role: "value.energy.consumption",
    type: "number",
    unit: "kWh",
    useDpScale: true,
  },
];

export const WATER_PUMP_NUMBER_DEFINITIONS: DpStateDefinition[] = [
  {
    id: "pump.speedSetpoint",
    dpId: "111",
    name: "Speed setpoint",
    role: "level.speed",
    type: "number",
    unit: "%",
    write: true,
    min: 30,
    max: 100,
    step: 1,
    useDpRange: true,
  },
  {
    id: "pump.backwashDuration",
    dpId: "104",
    name: "Backwash duration",
    role: "level.timer",
    type: "number",
    unit: "min",
    write: true,
    min: 0,
    max: 1440,
    step: 1,
    useDpRange: true,
    useDpTimeUnit: true,
  },
];
